### ISSUE TITLE
Rename the fork branch 'mmtk'

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/ruby#18]
Can you please rename the fork branch 'mmtk' for simplicity and consistency.

**Comment by wks** [comment]
Yes. I think that's simpler, too.

**Comment by wks** [comment]
I renamed the `third-party-heap` branch to `mmtk` on GitHub.

The merge targets of all PRs are automatically updated, too.

Developers need to update their local repositories.  The easiest way to do so is

```
git fetch --all
git checkout mmtk
```
